name: bloomista_app
description: "A new Flutter project."

# Prevent publishing to pub.dev (remove this line if you want to publish)
publish_to: 'none'

# Version and build number
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies your app needs
dependencies:
  flutter:
    sdk: flutter

  # Image picker package for selecting images from gallery/camera
  image_picker: ^1.2.2

  # Cupertino icons for iOS-style icons
  cupertino_icons: ^1.0.8

  # Shared Preferences package for saving user data locally
  shared_preferences: ^2.2.3

  # Provider package for state management across the app
  provider: ^6.1.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lint rules for clean code
  flutter_lints: ^6.0.0

flutter:
  # Enable Material icons (default Flutter icons)
  uses-material-design: true

  # Add assets (images, etc.) to your app
  # Here we include the entire images folder
  assets:
    - assets/images/
